# Generated by Django 3.2 on 2022-04-28 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecommerce.custom_auth.utils
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20220422_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, max_length=128, null=True, region=None, unique=True, verbose_name='Phone'),
        ),
        migrations.CreateModel(
            name='PasswordResetId',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expiration_time', models.DateTimeField(default=ecommerce.custom_auth.utils.set_password_reset_expiration_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password reset id',
            },
        ),
    ]
