# Generated by Django 3.2 on 2022-05-06 13:23

from django.db import migrations
import ecommerce.cart.managers


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('objects', ecommerce.cart.managers.CartManager()),
            ],
        ),
    ]
