# Generated by Django 3.2 on 2022-04-21 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ecommerce.utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='Object Id')),
                ('file', models.FileField(max_length=500, upload_to=ecommerce.utils.utils.get_document_path)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
