# Generated by Django 3.2 on 2022-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productphoto_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(error_messages={'unique': 'A product with that name already exists.'}, max_length=256, unique=True, verbose_name='name'),
        ),
    ]
